In [2]:
import pandas as pd

In [5]:
%pip install openpyxl

filename = "Lending-company.xlsx"
my_xlsx_data = pd.read_excel(filename)
my_xlsx_data

Requirement already satisfied: openpyxl in c:\users\binig\miniconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\binig\miniconda3\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

,LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,1,LoanID_1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
1,2,LoanID_2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
2,3,LoanID_3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
3,4,LoanID_4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
4,5,LoanID_5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,1039,LoanID_1039,Product B,Male,Location 73,Region 6,17300.0,29/12/2018,2200,45,365,3251,4743,16617,Finished Payment
1039,1040,LoanID_1040,Product A,Male,Location 82,Region 1,NaN,28/03/2018,2200,45,365,4090,5582,16617,Finished Payment
1040,1041,LoanID_1041,Product A,NotSpecified,Location 11,Region 4,17300.0,26/04/2018,2200,45,365,4051,5143,16617,Finished Payment
1041,1042,LoanID_1042,Product B,Female,Location 26,Region 6,16300.0,25/10/2016,1000,45,365,1930,3462,15617,Finished Payment
1042,1043,LoanID_1043,Product A,NotSpecified,Location 94,Region 6,17300.0,15/05/2019,2200,45,365,4451,4743,16617,Finished Payment

In [6]:
type(my_xlsx_data)

pandas.core.frame.DataFrame

In [ ]:
location_data = pd.read_csv(
    "Lending-company.csv",
    usecols=["StringID", "Location", "Region"],
    index_col="StringID",
)
location_data.head()

             Location    Region
StringID
LoanID_1   Location 3  Region 2
LoanID_2   Location 6  Region 6
LoanID_3   Location 8  Region 3
LoanID_4  Location 26  Region 2
LoanID_5  Location 34  Region 3

In [11]:
filename = "Lending-Company-Numeric-Data-NAN.csv"
my_csv_data = pd.read_csv(filename)
my_csv_data.head()

   2000;40;365;3121;4241;13621
0  2000;40;365;3061;4171;15041
1  1000;40;365;2160;3280;15340
2  2000;40;365;3041;4241;15321
3  2000;50;365;3470;4820;13720
4  2000;40;365;3201;4141;14141

In [14]:
my_csv_data = pd.read_csv(filename, sep=";", engine="python")
my_csv_data.head()

     2000    40    365    3121    4241    13621
0  2000.0  40.0  365.0  3061.0  4171.0  15041.0
1  1000.0  40.0  365.0  2160.0  3280.0  15340.0
2  2000.0  40.0  365.0  3041.0  4241.0  15321.0
3  2000.0  50.0  365.0  3470.0  4820.0  13720.0
4  2000.0  40.0  365.0  3201.0  4141.0  14141.0

In [21]:
df_usecols = pd.read_csv("Lending-company.csv", usecols=["Product"])
df_squeezProduct = df_usecols.squeeze("columns")
df_squeezProduct.head()

0    Product B
1    Product D
2    Product B
3    Product A
4    Product B
Name: Product, dtype: object

In [23]:
type(df_squeezProduct)

pandas.core.series.Series

In [18]:
df_single_col = pd.read_csv("Customer-Gender.csv")
df_single_col.head()

  CustomerGender
0         Female
1         Female
2           Male
3           Male
4         Female

In [20]:
df_single_col = pd.read_csv("Customer-Gender.csv")
df_squeez = df_single_col.squeeze("columns")
df_squeez.head()

0    Female
1    Female
2      Male
3      Male
4    Female
Name: CustomerGender, dtype: object

In [24]:
type(df_squeez)

pandas.core.series.Series